### PR TITLE
Fix for the top menu hover shading problem

### PR DESCRIPTION
**Pull request by ercchy**
Hi guys,
I was adding an event today and saw two little problems with the design. 
I am sending fixes for them.

In the page submenu, there is a problem on hover, where shading does not meet the height of the menu.
europe code week map of events

The other error is that modal window on the login page overflows the main menu.
europe code week login

I have also added a fix for the scoreboard rendering, which is also overflowing the menu.
europe code week events scoreboard

Thanks,
Erika

### CODE REVIEW

**Comment by mitio** [comment]
@sparkica @ercchy Is this ready for merging? I see the `in progress` label applied?

**Comment by ercchy** [comment]
As far as I am concerned it is ready, I am not exactly sure why the `in progress` label was added`. Maybe it was by accident @sparkica?

**Comment by mitio** [comment]
I also think it's good. Merging! Thank you @ercchy!

**Comment by mitio** [comment]
As a side note, in the future, when you send a new pull request, it's a good idea to make it from a feature branch. Also, it's better to rebase your feature branch on master, rather than merging master into the feature branch.

Read more about these two concepts here:
https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview

**Pull request merged**
