### PR TITLE
Remove only-EU country limitation

### PR DESCRIPTION
**Pull request by michelesr**
Authored by Alessandro Bogliolo

### CODE REVIEW

**Comment by mitio** [comment]
@michelesr Nice! :) Thanks! Will push it live now to see if it works.

**Comment by mitio** [comment]
Okay, @michelesr, after deploying live (yay for testing on production) we have an issue that all countries are listed on the homepage and we're missing the flags for most of them:

https://www.dropbox.com/s/xdqil3hq78esjmt/Screenshot%202015-09-28%2015.23.35.png?dl=0

Are you able to dig up flags for these and put them in the repo and send a new PR?

**Comment by michelesr** [comment]
Well... a filter for country with count of events >= 1 should be appropriated, so that flags for out of Europe countries can be added later by someone else.

**Comment by michelesr** [comment]
Is there a way (such as `bower install` or similar) to install static files? In my local environment the interface is missing static files.

**Comment by mitio** [comment]
This would be a good start. Thanks again!

**Comment by mitio** [comment]
As for the static files, after you've activated a virtual env and installed the dependencies (`pip install -r requirements.txt`), maybe these would help you:

```
./manage.py collectstatic --noinput
./manage.py compress
```

Or are you missing other files?

**Comment by michelesr** [comment]
After launching the first command i only miss `.png` files associated with flags

**Pull request merged**
