### PR TITLE
Changed theme topics list.

### PR DESCRIPTION
**Pull request by mihail-ivanov**
Fixing issue "Change the list of possible event topics in the events form" from trello.

### CODE REVIEW

**Comment by mitio** [comment]
Looks good, thanks!

**Comment by SteveClement** [comment]
@mihail-ivanov so if I want to add "Artificial intelligence" as an option I need to create a new file à la: 0009_update_eventtheme_list.py or should I just add the option "AI" to the 0008 script.
/cc @mitio

**Comment by mitio** [comment]
@SteveClement I haven't deployed the changes yet so I think it'd be best to just add it to the existing script. If you can, just add it in a separate PR. I will test it locally and if it works, I will mark the Trello task as completed.

**Comment by mitio** [comment]
Added AI.

**Pull request merged**
